language: go

go:
  - 1.10.x
  - 1.11.x
  - tip

branches:
  only:
    - master

cache:
  directories:
    - $GOCACHE
    - $GOPATH
    - $GOPATH/pkg/mod
    - $GOPATH/github.com/golang
    - $GOPATH/gopkg.in/alecthomas

install:
  - env GO111MODULE=on go install . ./cmd/...
  - env GO111MODULE=off go get -u github.com/alecthomas/gometalinter
  - env GO111MODULE=off gometalinter --install
  - env GO111MODULE=off go get -u github.com/go-task/task/cmd/task
  - go get -t ./...

script:
  - export PATH=$PATH:$HOME/gopath/bin
  - env GO111MODULE=on task ci
