language: go

branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

install:
  - GO111MODULE=on go install . ./cmd/...
  - GO111MODULE=off go get -u gopkg.in/alecthomas/gometalinter.v2
  - GO111MODULE=off gometalinter.v2 --install
  - go get -u -v github.com/go-task/task/cmd/task
  - task install

go:
  - "1.9"
  - "1.10"
  - tip

script:
  - task ci
